# Generated by Django 3.1.6 on 2021-04-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20210410_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
